<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>panda_integration_test</name>
  <version>0.0.0</version>
  <description>Package which runs the integration test</description>
  <maintainer email="sharathnp1998@gmail.com">sharathnpayyadi</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>python3</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_testing</exec_depend>
  <depend>panda_msgs</depend>
  <exec_depend>panda_bringup</exec_depend>
  <depend>panda_moveit_config</depend>
  <exec_depend>panda_object_detection</exec_depend>
  <depend>panda_motion_planning</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <test_depend>ament_cmake_ros</test_depend>
  <test_depend>launch</test_depend>
  <test_depend>launch_ros</test_depend>
  <test_depend>launch_testing</test_depend>
  <test_depend>launch_testing_ament_cmake</test_depend>
  <test_depend>rclpy</test_depend>
  <test_depend>turtlesim</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
